// Generated by D:\Coding\References\LittleTomato\2026-09-10\gen_stock_rigs.py
// from rig-manifest.json; do not edit by hand, rerun the generator instead.
import shinchan_feet from "./assets/characters/shinchan/feet.png";
import shinchan_ear_left from "./assets/characters/shinchan/ear-left.png";
import shinchan_ear_right from "./assets/characters/shinchan/ear-right.png";
import shinchan_body from "./assets/characters/shinchan/body.png";
import shinchan_arm_right from "./assets/characters/shinchan/arm-right.png";
import spongebob_feet from "./assets/characters/spongebob/feet.png";
import spongebob_body from "./assets/characters/spongebob/body.png";
import spongebob_arm_left from "./assets/characters/spongebob/arm-left.png";
import spongebob_arm_right from "./assets/characters/spongebob/arm-right.png";
import cinnamoroll_ear_left from "./assets/characters/cinnamoroll/ear-left.png";
import cinnamoroll_ear_right from "./assets/characters/cinnamoroll/ear-right.png";
import cinnamoroll_feet from "./assets/characters/cinnamoroll/feet.png";
import cinnamoroll_body from "./assets/characters/cinnamoroll/body.png";
import cinnamoroll_arm_left from "./assets/characters/cinnamoroll/arm-left.png";
import cinnamoroll_arm_right from "./assets/characters/cinnamoroll/arm-right.png";
import kuromi_ear_left from "./assets/characters/kuromi/ear-left.png";
import kuromi_ear_right from "./assets/characters/kuromi/ear-right.png";
import kuromi_body from "./assets/characters/kuromi/body.png";
import kuromi_arm_left from "./assets/characters/kuromi/arm-left.png";
import kuromi_arm_right from "./assets/characters/kuromi/arm-right.png";
import kuromi_feet from "./assets/characters/kuromi/feet.png";
import pooh_ear_left from "./assets/characters/pooh/ear-left.png";
import pooh_ear_right from "./assets/characters/pooh/ear-right.png";
import pooh_body from "./assets/characters/pooh/body.png";
import pooh_arm_left from "./assets/characters/pooh/arm-left.png";
import pooh_feet from "./assets/characters/pooh/feet.png";
import pikachu_ear_left from "./assets/characters/pikachu/ear-left.png";
import pikachu_ear_right from "./assets/characters/pikachu/ear-right.png";
import pikachu_feet from "./assets/characters/pikachu/feet.png";
import pikachu_body from "./assets/characters/pikachu/body.png";
import pikachu_arm_left from "./assets/characters/pikachu/arm-left.png";
import pikachu_arm_right from "./assets/characters/pikachu/arm-right.png";
import doraemon_feet from "./assets/characters/doraemon/feet.png";
import doraemon_body from "./assets/characters/doraemon/body.png";
import doraemon_arm_right from "./assets/characters/doraemon/arm-right.png";
import kirby_body from "./assets/characters/kirby/body.png";
import kirby_arm_left from "./assets/characters/kirby/arm-left.png";
import kirby_feet from "./assets/characters/kirby/feet.png";
import hello_kitty_ear_left from "./assets/characters/hello_kitty/ear-left.png";
import hello_kitty_body from "./assets/characters/hello_kitty/body.png";
import hello_kitty_arm_left from "./assets/characters/hello_kitty/arm-left.png";
import hello_kitty_arm_right from "./assets/characters/hello_kitty/arm-right.png";
import hello_kitty_feet from "./assets/characters/hello_kitty/feet.png";

export type StockLayer = {
  name: string; src: string; x: number; y: number;
  w: number; h: number; z: number; cls: string; origin?: [number, number];
};

export type StockEyes = {
  boxes: { cx: number; cy: number; rx: number; ry: number;
    pupil: { fill: string; hi: number; inner?: { rx: number; ry: number; fill: string } };
    glint?: { cx: number; cy: number; rx: number; ry: number; fill: string };
    lid: { rx: number; ry: number; fill: string } }[];
  arcs: { d: string; stroke: string; width: number };
};

export type StockRig = { width: number; height: number; layers: StockLayer[]; eyes?: StockEyes };

export const stockRigs = {
  shinchan: {
    width: 330, height: 366,
    layers: [
      { name: "feet", src: shinchan_feet, x: 136, y: 296, w: 57, h: 58, z: 1, cls: "rig-foot" },
      { name: "ear-left", src: shinchan_ear_left, x: 108, y: 98, w: 48, h: 56, z: 1, cls: "rig-ear rig-ear-left", origin: [146, 130] },
      { name: "ear-right", src: shinchan_ear_right, x: 280, y: 104, w: 3, h: 16, z: 1, cls: "rig-ear rig-ear-right", origin: [288, 134] },
      { name: "body", src: shinchan_body, x: 0, y: 0, w: 330, h: 366, z: 2, cls: "" },
      { name: "arm-right", src: shinchan_arm_right, x: 12, y: 103, w: 57, h: 58, z: 3, cls: "rig-arm rig-arm-right", origin: [55, 150] },
    ],
  eyes: {
    boxes: [{ cx: 154, cy: 90, rx: 15.4, ry: 20.6, pupil: { fill: "#2d2620", hi: 4.0 }, lid: { rx: 19.4, ry: 24.6, fill: "#fbd4ab" } }, { cx: 220, cy: 78, rx: 6.2, ry: 17.8, pupil: { fill: "#2d2620", hi: 4.0 }, lid: { rx: 10.2, ry: 21.8, fill: "#fbd4ab" } }],
    arcs: { d: "M M", stroke: "#43342a", width: 7 },
  },
  },
  spongebob: {
    width: 892, height: 880,
    layers: [
      { name: "feet", src: spongebob_feet, x: 258, y: 634, w: 428, h: 223, z: 1, cls: "rig-foot" },
      { name: "body", src: spongebob_body, x: 0, y: 0, w: 892, h: 880, z: 2, cls: "" },
      { name: "arm-left", src: spongebob_arm_left, x: 38, y: 104, w: 233, h: 208, z: 3, cls: "rig-arm rig-arm-left", origin: [190, 292] },
      { name: "arm-right", src: spongebob_arm_right, x: 595, y: 120, w: 197, h: 137, z: 3, cls: "rig-arm rig-arm-right", origin: [700, 282] },
    ],
  eyes: {
    boxes: [{ cx: 383, cy: 186, rx: 25.9, ry: 35.0, pupil: { fill: "#3ba7e2", hi: 9, inner: { rx: 11.7, ry: 15.8, fill: "#141d38" } }, lid: { rx: 29.9, ry: 39.0, fill: "#ffffff" } }, { cx: 512, cy: 176, rx: 26.9, ry: 37.9, pupil: { fill: "#3ba7e2", hi: 9, inner: { rx: 12.1, ry: 17.1, fill: "#141d38" } }, lid: { rx: 30.9, ry: 41.9, fill: "#ffffff" } }],
    arcs: { d: "M M", stroke: "#141d38", width: 14 },
  },
  },
  cinnamoroll: {
    width: 946, height: 473,
    layers: [
      { name: "ear-left", src: cinnamoroll_ear_left, x: 28, y: 34, w: 288, h: 182, z: 1, cls: "rig-ear rig-ear-left", origin: [296, 112] },
      { name: "ear-right", src: cinnamoroll_ear_right, x: 594, y: 70, w: 324, h: 178, z: 1, cls: "rig-ear rig-ear-right", origin: [618, 112] },
      { name: "feet", src: cinnamoroll_feet, x: 362, y: 396, w: 206, h: 49, z: 1, cls: "rig-foot" },
      { name: "body", src: cinnamoroll_body, x: 0, y: 0, w: 946, h: 473, z: 2, cls: "" },
      { name: "arm-left", src: cinnamoroll_arm_left, x: 344, y: 245, w: 112, h: 87, z: 3, cls: "rig-arm rig-arm-left", origin: [418, 246] },
      { name: "arm-right", src: cinnamoroll_arm_right, x: 454, y: 252, w: 110, h: 68, z: 3, cls: "rig-arm rig-arm-right", origin: [498, 240] },
    ],
  eyes: {
    boxes: [{ cx: 349, cy: 154, rx: 16.3, ry: 23.0, pupil: { fill: "#2ba3dd", hi: 7 }, lid: { rx: 20.3, ry: 27.0, fill: "#ffffff" } }, { cx: 560, cy: 178, rx: 15.8, ry: 22.1, pupil: { fill: "#2ba3dd", hi: 7 }, lid: { rx: 19.8, ry: 26.1, fill: "#ffffff" } }],
    arcs: { d: "M M", stroke: "#1f7fae", width: 11 },
  },
  },
  kuromi: {
    width: 479, height: 571,
    layers: [
      { name: "ear-left", src: kuromi_ear_left, x: 19, y: 27, w: 173, h: 155, z: 1, cls: "rig-ear rig-ear-left", origin: [150, 152] },
      { name: "ear-right", src: kuromi_ear_right, x: 288, y: 18, w: 173, h: 154, z: 1, cls: "rig-ear rig-ear-right", origin: [326, 150] },
      { name: "body", src: kuromi_body, x: 0, y: 0, w: 479, h: 571, z: 2, cls: "" },
      { name: "arm-left", src: kuromi_arm_left, x: 133, y: 400, w: 44, h: 68, z: 3, cls: "rig-arm rig-arm-left", origin: [162, 408] },
      { name: "arm-right", src: kuromi_arm_right, x: 284, y: 400, w: 63, h: 80, z: 3, cls: "rig-arm rig-arm-right", origin: [312, 402] },
      { name: "feet", src: kuromi_feet, x: 153, y: 468, w: 175, h: 81, z: 3, cls: "rig-foot" },
    ],
  eyes: {
    boxes: [{ cx: 172, cy: 304, rx: 17.8, ry: 27.4, pupil: { fill: "#211c27", hi: 6 }, lid: { rx: 21.8, ry: 31.4, fill: "#ffffff" } }, { cx: 314, cy: 304, rx: 17.8, ry: 27.4, pupil: { fill: "#211c27", hi: 6 }, lid: { rx: 21.8, ry: 31.4, fill: "#ffffff" } }],
    arcs: { d: "M M", stroke: "#211c27", width: 11 },
  },
  },
  pooh: {
    width: 407, height: 880,
    layers: [
      { name: "ear-left", src: pooh_ear_left, x: 146, y: 23, w: 100, h: 103, z: 1, cls: "rig-ear rig-ear-left", origin: [196, 108] },
      { name: "ear-right", src: pooh_ear_right, x: 294, y: 92, w: 90, h: 114, z: 1, cls: "rig-ear rig-ear-right", origin: [352, 148] },
      { name: "body", src: pooh_body, x: 0, y: 0, w: 407, h: 880, z: 2, cls: "" },
      { name: "arm-left", src: pooh_arm_left, x: 34, y: 421, w: 228, h: 131, z: 3, cls: "rig-arm rig-arm-left", origin: [55, 390] },
      { name: "feet", src: pooh_feet, x: 48, y: 722, w: 255, h: 132, z: 3, cls: "rig-foot" },
    ],
  eyes: {
    boxes: [{ cx: 172, cy: 190, rx: 8.2, ry: 8.6, pupil: { fill: "#2c1f08", hi: 3.2 }, lid: { rx: 12.2, ry: 12.6, fill: "#fdbe57" } }, { cx: 264, cy: 224, rx: 7.7, ry: 7.2, pupil: { fill: "#2c1f08", hi: 3.2 }, lid: { rx: 11.7, ry: 11.2, fill: "#fdbe57" } }],
    arcs: { d: "M M", stroke: "#46320e", width: 6 },
  },
  },
  pikachu: {
    width: 580, height: 545,
    layers: [
      { name: "ear-left", src: pikachu_ear_left, x: 90, y: 18, w: 82, h: 140, z: 1, cls: "rig-ear rig-ear-left", origin: [128, 142] },
      { name: "ear-right", src: pikachu_ear_right, x: 252, y: 88, w: 180, h: 110, z: 1, cls: "rig-ear rig-ear-right", origin: [262, 140] },
      { name: "feet", src: pikachu_feet, x: 176, y: 470, w: 203, h: 54, z: 1, cls: "rig-foot" },
      { name: "body", src: pikachu_body, x: 0, y: 0, w: 580, h: 545, z: 2, cls: "" },
      { name: "arm-left", src: pikachu_arm_left, x: 17, y: 295, w: 85, h: 65, z: 3, cls: "rig-arm rig-arm-left", origin: [88, 312] },
      { name: "arm-right", src: pikachu_arm_right, x: 212, y: 278, w: 76, h: 76, z: 3, cls: "rig-arm rig-arm-right", origin: [240, 300] },
    ],
  eyes: {
    boxes: [{ cx: 82, cy: 204, rx: 12.0, ry: 16.8, pupil: { fill: "#2d2620", hi: 3.5 }, lid: { rx: 16.0, ry: 20.8, fill: "#fae37d" } }, { cx: 184, cy: 184, rx: 17.8, ry: 17.3, pupil: { fill: "#2d2620", hi: 3.5 }, lid: { rx: 21.8, ry: 21.3, fill: "#fbe47e" } }],
    arcs: { d: "M M", stroke: "#43342a", width: 6 },
  },
  },
  doraemon: {
    width: 534, height: 760,
    layers: [
      { name: "feet", src: doraemon_feet, x: 264, y: 460, w: 146, h: 61, z: 1, cls: "rig-foot" },
      { name: "body", src: doraemon_body, x: 0, y: 0, w: 534, h: 760, z: 2, cls: "" },
      { name: "arm-right", src: doraemon_arm_right, x: 130, y: 228, w: 113, h: 114, z: 3, cls: "rig-arm rig-arm-right", origin: [228, 300] },
    ],
  eyes: {
    boxes: [{ cx: 290, cy: 178, rx: 26.9, ry: 26.9, pupil: { fill: "#222222", hi: 3.5 }, lid: { rx: 30.9, ry: 30.9, fill: "#ffffff" } }, { cx: 345, cy: 182, rx: 26.9, ry: 26.9, pupil: { fill: "#222222", hi: 3.5 }, lid: { rx: 30.9, ry: 30.9, fill: "#fffffe" } }],
    arcs: { d: "M M", stroke: "#222222", width: 9 },
  },
  },
  kirby: {
    width: 950, height: 880,
    layers: [
      { name: "body", src: kirby_body, x: 0, y: 0, w: 950, h: 880, z: 2, cls: "" },
      { name: "arm-left", src: kirby_arm_left, x: 62, y: 535, w: 97, h: 236, z: 3, cls: "rig-arm rig-arm-left", origin: [150, 555] },
      { name: "feet", src: kirby_feet, x: 198, y: 512, w: 710, h: 326, z: 3, cls: "rig-foot" },
    ],
  eyes: {
    boxes: [{ cx: 517, cy: 334, rx: 36.5, ry: 82.1, pupil: { fill: "#1c2f6b", hi: 0 }, glint: { cx: 517, cy: 300, rx: 20, ry: 29, fill: "#eaf2ff" }, lid: { rx: 40.5, ry: 86.1, fill: "#ffbaeb" } }, { cx: 632, cy: 342, rx: 36.0, ry: 82.1, pupil: { fill: "#1c2f6b", hi: 0 }, glint: { cx: 632, cy: 308, rx: 20, ry: 29, fill: "#eaf2ff" }, lid: { rx: 40.0, ry: 86.1, fill: "#ffacdc" } }],
    arcs: { d: "M M", stroke: "#18203b", width: 11 },
  },
  },
  hello_kitty: {
    width: 960, height: 606,
    layers: [
      { name: "ear-left", src: hello_kitty_ear_left, x: 333, y: 36, w: 69, h: 84, z: 1, cls: "rig-ear rig-ear-left", origin: [368, 96] },
      { name: "body", src: hello_kitty_body, x: 0, y: 0, w: 960, h: 606, z: 2, cls: "" },
      { name: "arm-left", src: hello_kitty_arm_left, x: 468, y: 454, w: 73, h: 59, z: 3, cls: "rig-arm rig-arm-left", origin: [470, 402] },
      { name: "arm-right", src: hello_kitty_arm_right, x: 610, y: 455, w: 82, h: 93, z: 3, cls: "rig-arm rig-arm-right", origin: [650, 432] },
      { name: "feet", src: hello_kitty_feet, x: 375, y: 486, w: 317, h: 81, z: 3, cls: "rig-foot" },
    ],
  eyes: {
    boxes: [{ cx: 412, cy: 277, rx: 17.3, ry: 21.1, pupil: { fill: "#1a1a1a", hi: 3.5 }, lid: { rx: 21.3, ry: 25.1, fill: "#ffffff" } }, { cx: 638, cy: 277, rx: 16.8, ry: 21.1, pupil: { fill: "#1a1a1a", hi: 3.5 }, lid: { rx: 20.8, ry: 25.1, fill: "#ffffff" } }],
    arcs: { d: "M M", stroke: "#2a2020", width: 8 },
  },
  },
} as const satisfies Record<string, StockRig>;
